### ISSUE TITLE
Todo modification

### ISSUE THREAD

**Issue by Shimstache** [CyberSecurityN00b/penzsh#1]
if running "pz todo" with no arguments it creates an entry with no data
Creates the following output

pz todos
     1	 
     2	test
     3	
     4	testing

If trying to delete the empty rows with pz todone, an error shows 
pz todone 3
PENZSH >>> There aren't that many tasks!

**Comment by CyberSecurityN00b** [comment]
Fix implemented, will be pushed after testing.
