### ISSUE TITLE
LHOST getting set to 1000 whenever entering a certain project folder

### ISSUE THREAD

**Issue by PortWhisperer** [CyberSecurityN00b/penzsh#4]
see image.
Adjusting PENZSH_LHOST manually only persists while in the folder. Re-entering folder causes it to reset to 1000; seems like a bug.
https://imgur.com/a/lvupeqI

I'll submit PR if i get time to investigate..

**Comment by CyberSecurityN00b** [comment]
Pretty sure I've fixed it with f5523c34baa4ffbea5113d8ebd92dd393c483249, if you can confirm for you before I close this. Was based on an assumption on my part on which column/word of the output would have the results. The grep regex should fix it, fingers crossed.

**Comment by CyberSecurityN00b** [comment]
Closing due to no response. Please resubmit if the issue continues. Thank you!
